// Generated by SciMLWasm.write_opcodes_js from src/bytecode.jl. Do not edit;
// run examples/generic/compile.jl (or write_opcodes_js) to refresh.
export const OP = {
  CONST: 0,
  U: 1,
  P: 2,
  T: 3,
  ADD: 4,
  SUB: 5,
  MUL: 6,
  DIV: 7,
  POW: 8,
  NEG: 9,
  SIN: 10,
  COS: 11,
  TAN: 12,
  EXP: 13,
  LOG: 14,
  SQRT: 15,
  ABS: 16,
  TANH: 17,
  SINH: 18,
  COSH: 19,
  ATAN: 20,
  MIN: 21,
  MAX: 22,
  END: 23,
};
export const UNARY = { sin: OP.SIN, cos: OP.COS, tan: OP.TAN, exp: OP.EXP, log: OP.LOG, sqrt: OP.SQRT, abs: OP.ABS, tanh: OP.TANH, sinh: OP.SINH, cosh: OP.COSH, atan: OP.ATAN };
export const BINARY = { min: OP.MIN, max: OP.MAX };
export const MAX_DIM = 8;
export const STACK_DEPTH = 64;
