# The stack machine that evaluates a user's equations. Equations arrive as
# bytecode from JS, so one compiled module solves any first-order system.

# Opcodes must match examples/generic/parser.mjs. CONST, U and P take the
# next word as a 1-based operand.
const OP_CONST = Int32(0)
const OP_U     = Int32(1)
const OP_P     = Int32(2)
const OP_T     = Int32(3)
const OP_ADD   = Int32(4)
const OP_SUB   = Int32(5)
const OP_MUL   = Int32(6)
const OP_DIV   = Int32(7)
const OP_POW   = Int32(8)
const OP_NEG   = Int32(9)
const OP_SIN   = Int32(10)
const OP_COS   = Int32(11)
const OP_TAN   = Int32(12)
const OP_EXP   = Int32(13)
const OP_LOG   = Int32(14)
const OP_SQRT  = Int32(15)
const OP_ABS   = Int32(16)
const OP_TANH  = Int32(17)
const OP_SINH  = Int32(18)
const OP_COSH  = Int32(19)
const OP_ATAN  = Int32(20)
const OP_MIN   = Int32(21)
const OP_MAX   = Int32(22)
const OP_END   = Int32(23)

const STACK_DEPTH = 64
const MAX_DIM = 8

# The bytecode contract in one place. `write_opcodes_js` emits it for the
# browser parser, so the two sides cannot disagree.
const OPCODES = (
    CONST = OP_CONST, U = OP_U, P = OP_P, T = OP_T,
    ADD = OP_ADD, SUB = OP_SUB, MUL = OP_MUL, DIV = OP_DIV, POW = OP_POW, NEG = OP_NEG,
    SIN = OP_SIN, COS = OP_COS, TAN = OP_TAN, EXP = OP_EXP, LOG = OP_LOG, SQRT = OP_SQRT,
    ABS = OP_ABS, TANH = OP_TANH, SINH = OP_SINH, COSH = OP_COSH, ATAN = OP_ATAN,
    MIN = OP_MIN, MAX = OP_MAX, END = OP_END,
)
# Function names the parser accepts, by arity, mapped to their opcodes.
const UNARY_FUNCS = (sin = OP_SIN, cos = OP_COS, tan = OP_TAN, exp = OP_EXP, log = OP_LOG,
                     sqrt = OP_SQRT, abs = OP_ABS, tanh = OP_TANH, sinh = OP_SINH,
                     cosh = OP_COSH, atan = OP_ATAN)
const BINARY_FUNCS = (min = OP_MIN, max = OP_MAX)

"""
    opcodes_js() -> String

The JavaScript module the browser parser imports: the opcode table, the
function tables, and the limits, generated from the constants above.
"""
function opcodes_js()
    io = IOBuffer()
    println(io, "// Generated by SciMLWasm.write_opcodes_js from src/bytecode.jl. Do not edit;")
    println(io, "// run examples/generic/compile.jl (or write_opcodes_js) to refresh.")
    println(io, "export const OP = {")
    for (k, v) in pairs(OPCODES)
        println(io, "  ", k, ": ", v, ",")
    end
    println(io, "};")
    println(io, "export const UNARY = { ", join(("$k: OP.$(uppercase(String(k)))" for k in keys(UNARY_FUNCS)), ", "), " };")
    println(io, "export const BINARY = { ", join(("$k: OP.$(uppercase(String(k)))" for k in keys(BINARY_FUNCS)), ", "), " };")
    println(io, "export const MAX_DIM = ", MAX_DIM, ";")
    println(io, "export const STACK_DEPTH = ", STACK_DEPTH, ";")
    return String(take!(io))
end

"""
    write_opcodes_js(path) -> path

Write [`opcodes_js`](@ref) to `path`.
"""
function write_opcodes_js(path::AbstractString)
    write(path, opcodes_js())
    return path
end

"""
    Program(code, starts, consts, params, stack, du)

A bytecode system. `code` holds all equations back to back and `starts[k]` is
the index in `code` where equation `k` begins. `stack` and `du` are scratch
buffers allocated once per solve.
"""
struct Program
    code::Vector{Int32}
    starts::Vector{Int32}
    consts::Vector{Float64}
    params::Vector{Float64}
    stack::Vector{Float64}
    du::Vector{Float64}
end

# Small integer exponents by repeated multiplication so `x^2` matches Julia's
# `literal_pow` lowering bit for bit.
@inline function powi(x::Float64, y::Float64)::Float64
    n = round(y)
    if n == y && abs(n) <= 16.0
        k = Int(n)
        b = x
        if k < 0
            b = 1.0 / x
            k = -k
        end
        r = 1.0
        for _ in 1:k
            r *= b
        end
        return r
    end
    return x^y
end

"""
    run_program(p::Program, k, u, t)

Evaluate equation `k` of `p` at state `u` and time `t`.
"""
function run_program(p::Program, k::Int, u, t::Float64)::Float64
    code = p.code
    st = p.stack
    pc = Int(p.starts[k])
    sp = 0
    while true
        op = code[pc]
        pc += 1
        if op == OP_CONST
            sp += 1
            st[sp] = p.consts[code[pc]]
            pc += 1
        elseif op == OP_U
            sp += 1
            st[sp] = u[code[pc]]
            pc += 1
        elseif op == OP_P
            sp += 1
            st[sp] = p.params[code[pc]]
            pc += 1
        elseif op == OP_T
            sp += 1
            st[sp] = t
        elseif op == OP_ADD
            st[sp - 1] = st[sp - 1] + st[sp]
            sp -= 1
        elseif op == OP_SUB
            st[sp - 1] = st[sp - 1] - st[sp]
            sp -= 1
        elseif op == OP_MUL
            st[sp - 1] = st[sp - 1] * st[sp]
            sp -= 1
        elseif op == OP_DIV
            st[sp - 1] = st[sp - 1] / st[sp]
            sp -= 1
        elseif op == OP_POW
            st[sp - 1] = powi(st[sp - 1], st[sp])
            sp -= 1
        elseif op == OP_NEG
            st[sp] = -st[sp]
        elseif op == OP_SIN
            st[sp] = sin(st[sp])
        elseif op == OP_COS
            st[sp] = cos(st[sp])
        elseif op == OP_TAN
            st[sp] = tan(st[sp])
        elseif op == OP_EXP
            st[sp] = exp(st[sp])
        elseif op == OP_LOG
            st[sp] = log(st[sp])
        elseif op == OP_SQRT
            st[sp] = sqrt(st[sp])
        elseif op == OP_ABS
            st[sp] = abs(st[sp])
        elseif op == OP_TANH
            st[sp] = tanh(st[sp])
        elseif op == OP_SINH
            st[sp] = sinh(st[sp])
        elseif op == OP_COSH
            st[sp] = cosh(st[sp])
        elseif op == OP_ATAN
            st[sp] = atan(st[sp])
        elseif op == OP_MIN
            st[sp - 1] = min(st[sp - 1], st[sp])
            sp -= 1
        elseif op == OP_MAX
            st[sp - 1] = max(st[sp - 1], st[sp])
            sp -= 1
        elseif op == OP_END
            return st[sp]
        else
            return NaN
        end
    end
end

"""
    eval_expr(code, starts, consts, params, u, t, k)

Evaluate equation `k` from raw bytecode arrays. Exported to wasm so the JS
side can check the interpreter against its own evaluator.
"""
function eval_expr(code::Vector{Int32}, starts::Vector{Int32}, consts::Vector{Float64},
                   params::Vector{Float64}, u::Vector{Float64}, t::Float64, k::Int32)::Float64
    p = Program(code, starts, consts, params,
                Vector{Float64}(undef, STACK_DEPTH), Vector{Float64}(undef, 1))
    return run_program(p, Int(k), u, t)
end
